version: "3.8"

services:
  servicea:
    build:
      context: ./serviceA
    volumes:
      - serviceA-data:/usr/src/app
    ports:
      - "4000:4000"

  sidecar:
    build:
      context: ./sidecar
    volumes:
      - serviceA-data:/usr/src/app

volumes:
  serviceA-data:
