name: node.js CI

# declenceher event
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


# jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4