name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          working-directory: serviceA

      - name: Install dependencies
        run: npm ci
        working-directory: serviceA

      - name: Run build (if present)
        run: npm run build --if-present
        working-directory: serviceA

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: ./serviceA
          file: ./serviceA/Dockerfile
          push: true
          tags: yousssefb/docker25:latest